syntax = "proto3";

import "google/protobuf/struct.proto";
import "google/protobuf/wrappers.proto";

option java_multiple_files = true;
option java_package = "org.apache.solux.types";
option java_outer_classname = "SoluxTypes";
option objc_class_prefix = "Solux";

package solux.proto;


/*
 Using the well-known-type of google.protobuf.Struct doc = 1
 allows {"doc":{"myint":77, "mystr":"foo"}}
 Unfortunately, that's not enough types!
 Replicating Struct myself requires this really verbose JSON to send to evans:
{
  "doc": {
    "fields": {
      "myint": {
        "number_value": 77
      },
      "mystr": {
        "string_value": "foo"
      }
    }
  }
}
*/


// Proto notes:
// can't repeat oneof fields or map fields
// can't have map as value in map


/// The target of this operation
message Target {
  repeated string name = 1;  // qualified collection name

  // An API-key could reference an existing Library that would be the root for further qualifying the collection name.
  // Thus a user would not need to know where in the hierarchy they are.  Responses containing collection names should
  // likewise only contain collection names qualified from this reference point.
}


message SearchRequest {
  // request_id is optional and opaque (server does not care what the value is).  If provided, the server will
  // use it in the response.
  bytes request_id = 1;
  Target collection = 2;

  // An alternative could be to put the tag/name in the SearchOp itself
  map<string, SearchOp> ops = 3;
}

message SearchOp {
  oneof kind {
    TopDocs top_docs = 1;
    // future: function (or leave that as a query type?)
    FieldFacet field_facet = 8;
    // future: something like terms component... stream out all terms of one or more (or all) fields
  }
}

message TopDocs {
  Query query = 1;
  int64 offset = 2;
  optional sint64 limit = 3;
  bool get_matches = 4;         // return the number of matching documents
  bool get_scores = 5;          // return the relevancy score for each document returned
  repeated string fields = 6;   // fields to return for each document
  repeated SortSpec sorts = 7;
}

message SortSpec {
  string field = 1;
  // future: sort by function

  enum SortDir {
    option allow_alias = true;
    UNKNOWN = 0;
    ASC = 1;
    ASCENDING = 1;
    DESC = 2;
    DESCENDING = 2;
  }
  SortDir dir = 10;
}

message Query {
  oneof kind {
    Match match = 1;
    BooleanQuery boolean = 2;
    bool all = 3;                   // selects all documents
    string field = 4;               // selects all documents with the given field name.  // TODO: what about field regex?

    // TODO: a looser string match that will auto-convert to correct type
    // TODO: a text query type (parsed by QueryParser)
    // TODO: wildcard query
    // TODO: phrase query
    // TODO: function?


  }


}

  // use NamedValue here instead? Repeat field so this can be used to query multiple fields at once? Add a field regex?
  // the alternative is to add more query types at the top level to be more explicit
message Match {
  string field = 1;
  Val val = 2;   // if val is an Array, this could be used for TermsQuery as well...  how to tell if scoring or not though?
}

message BooleanQuery {
  repeated Query filter = 1;       // required clauses that do not add to the score
  repeated Query required = 2;     // required clauses that do add to the score
  repeated Query optional = 3;     // optional clauses that add to the score
  repeated Query prohibited = 4;   // prohibited clauses that must not match
  int32 min_match = 5;             // minimum number of optional clauses that must match
}


message FieldFacet {
  string field = 1;
  map<string, SearchOp> ops = 2;  // sub-facets or search operations performed per bucket
}


// Top-level response to a Search request
message SearchResponse {
  map<string, SearchResult> ops = 3;
}

message SearchResult {
  oneof kind {
    DocList docs = 1;
  }
}

message DocList {
  sint64 matches = 1;
  float max_score = 2;
  Columns columns = 3;
  int64 offset = 4;
  bool more = 5; // expect more results to be streamed back?
}

// TODO: a column format for facets for better efficiency (so string names and protobuf tags aren't repeated for each bucket?)
// may be more efficient client language mapping as well?
// What about special buckets then?  Map to a column number?  See FacetResponse below for a prototype column response
message BucketList {
  repeated Bucket buckets = 1;
  sint64 num_buckets = 2;  // The total number of buckets *if* it was requested.  This can be expensive to calculate.
  int64 offset = 3;
  // TODO: a more flag if streaming for this bucket list?
}

message Bucket {
  Val val = 1;
  sint64 count = 2;
  map<string, SearchResult> ops = 3;
}

message FacetResponse {
  sint64 num_buckets =  1;
  // TODO: for a field facet, the values will be string,binary,integer, or boolean.  We could also use
  // the array type embedded in a single Val (i.e. don't have this field repeated) for a tigher response type.
  repeated Val bucket_ids = 2;
  repeated int64 counts = 3;
  Columns columns = 4;  // other custom values requested for this facet, like min(price) for example
}



//
//  Indexing
//

message UpdateRequest {
  // request_id is optional and opaque (server does not care what the value is).  If provided, the server will
  // use it in the UpdateResponse.  This is useful for the client to correlate requests and responses in
  // streaming RPCs.
  bytes request_id = 1;

  // stream_id is optional.  When in streaming mode,
  // Update messages in the same logical stream will be processed serially.  A stream_id of 0
  int64 stream_id = 2;

  Target collection = 3;

  // TODO:
  // possible parameters: commitWithin,
  // optional batchId - in streaming request/responses, used to tell what batch has been indexed
  // optional stream - what logical stream this batch is part of (don't reorder docs in the same stream)
  //   or should this just be a separate streaming request for a separate stream?  That might be more difficult for some clients.



  // TODO: should docs/columns be wrapped in "oneof" (if so, need wrapper for "repeated Map docs")

  // documents represented as multiple rows... less efficient since field names are repeated for each document
  repeated Map docs = 4;

  // Column representation of a batch of documents.  All columns should have the same length.
  // For very sparse columns that you do not wish to represent as columns, use a special
  // field name of "_fields_" with a value of ColMap for per-document sparse values.  This is
  // effectively a mix of column oriented and row oriented.
  Columns columns = 5;
}

// The response to an update request, or one or more update requests in streaming mode.
message UpdateResponse {
  repeated SingleUpdateResponse responses = 1;
}

message SingleUpdateResponse {
  bytes request_id = 1;
  repeated UpdateError errors = 2;
}

message UpdateError {
  // docId... bytes? string?
  string error_message = 1;
}


// name : value
message NamedValue {
  string name = 1;
  Val val = 2;
}

message Map {
  // Unordered map of dynamically typed values.
  map<string, Val> fields = 1;
}

// like a Map, but the values are column types
message Columns {
  map<string, Column> columns = 1;
}

message Val {
  oneof kind {
    // Represents a null value.
    google.protobuf.NullValue null = 1;
    string s = 2;
    sint64 i = 3;  // since the encoding is the same, we don't bother distinguishing between 32 and 64 bit int
    double d = 4;
    float f = 5;
    bool b = 6;
    bytes bin = 7;
    Map map = 8;
    ArrVal arr = 9;
    ArrStr arr_s = 10;
    ArrInt arr_i = 11;
    ArrFloat arr_f = 12;
    ArrDouble arr_d = 13;
  }
}

message ArrVal {
  // Repeated field of dynamically typed values.
  repeated Val v = 1;
}

message ArrStr {
  repeated string v = 1;
}

message ArrInt {
  repeated sint64 v = 1;
}

message ArrFloat {
  repeated float v = 1;
}

message ArrDouble {
  repeated double v = 1;
}

// although the encoding is the same, the stub mapping is not and could blow up memory for large arrays
// if we always use 64 byte ints.
// TODO: if we can do custom decoding, an array that specifies a min/max would be even more efficient
message ArrInt32 {
  repeated sint32 v = 1;
}

message ColStr {
  // this will cause an additional tag (byte) per string value, but strings are normally somewhat larger anyway
  repeated google.protobuf.StringValue v = 1;
 /*
  optional string missingVal = 1;
  repeated string v = 2;
 */
}

// The distinction between a column and an array is that column values are somehow "nullable".
// This is a requirement to get different columns to "line up" if there mare missing values
// in some of them.
message Column {
  oneof kind {
    ColStr col_s = 1;
    ColInt col_i = 2;
    ColFloat col_f = 3;
    ColDouble col_d = 4;
    ColMap col_map = 14;
    ArrVal col_val = 15; // array-of-value is already nullable, so we don't have a separate column type for it
  }
}

message ColInt {
  optional sint64 missing_val = 1;
  repeated sint64 v = 2;
}

message ColFloat {
  optional float missing_val = 1;
  repeated float v = 2;
}

message ColDouble {
  optional double missing_val = 1;
  repeated double v = 2;
}

message ColMap {
  repeated Map v = 1;
}

