edition = "2023";

import "google/protobuf/cpp_features.proto";
option features.(pb.cpp).string_type = VIEW;

import "google/protobuf/struct.proto";
import "google/protobuf/wrappers.proto";

option java_multiple_files = true;
option java_package = "org.apache.solux.types";
option java_outer_classname = "SoluxTypes";
option objc_class_prefix = "Solux";

package solux.proto;


/// The target of this operation
message Target {
  repeated string name = 1;  // qualified collection name

  // Solux developers implementing a multi-tenant system could use an API-key (at a higher level... not in solux) as
  // a starting point akin to a current-working-directory to qualify the collection name.
  // Responses containing collection names should likewise be relative.
}

// Top-level search request that can contain multiple search operations.
message SearchRequest {
  // request_id is optional and opaque (server does not care what the value is).  If provided, the server will
  // echo it in the response.  Only really needed when a client streams multiple requests in the same RPC.
  bytes request_id = 1;
  Target collection = 2;

  // Multiple search operations in a single request.
  // An alternative could be to put the tag/name in the SearchOp itself
  map<string, SearchOp> ops = 3;

  // index view freshness requirement in microseconds. 0 (the default) means latest commit must be used.
  uint64 freshness_us = 4;
}

// Different types of top-level search operations.
message SearchOp {
  oneof kind {
    TopDocs top_docs = 1;
    // future: function (or leave that as a query type?)

    // TODO: hmmm, should different facet types be be encapsulated by a single "Facet" message?
    FieldFacet field_facet = 8;
    // future: something like terms component... stream out all terms of one or more (or all) fields
  }
}

message TopDocs {
  Query query = 1;
  // A set of named filters on the main query.
  repeated NamedQuery filter = 2;
  int64 offset = 3;
  sint64 limit = 4;
  bool get_number = 5;          // return the number of matching documents
  bool get_scores = 6;          // return the relevancy score for each document returned
  repeated string fields = 7;   // fields to return for each document
  repeated SortSpec sorts = 8;
  int32 batch_size = 9;         // maximum number of documents to return in a single streaming response
                                // if max_batch_size >= limit, multiple responses may be generated
                                // The solux server may choose a lower value to protect against large in-memory responses.
}

message SortSpec {
  string field = 1;
  // future: sort by function

  enum SortDir {
    option allow_alias = true;
    UNKNOWN = 0;
    ASC = 1;
    ASCENDING = 1;
    DESC = 2;
    DESCENDING = 2;
  }
  SortDir dir = 10;
}

message Query {
  oneof kind {
    Match match = 1;                // selects all documents with a value match in the specified field
    BooleanQuery boolean = 2;
    bool all = 3;                   // selects all documents
    string field = 4;               // selects all documents with the given field name.  // TODO: what about field regex?
    PhraseQuery phrase = 5;         // selects all documents with a phrase

    // TODO: a looser string match that will auto-convert to correct type
    // TODO: a text query type (parsed by QueryParser)
    // TODO: wildcard query
    // TODO: function?


  }


}

  // use NamedValue here instead? Repeat field so this can be used to query multiple fields at once? Add a field glob/regex?
  // the alternative is to add more query types at the top level to be more explicit
message Match {
  string field = 1;
  Val val = 2;   // if val is an Array, this could be used for TermsQuery as well...  how to tell if scoring or not though?
}

// Attach a name to a query so it can be referenced by other queries or facets.
message NamedQuery {
  string name = 1;
  Query query = 2;
}

message BooleanQuery {
  repeated Query filter = 1;       // required clauses that do not add to the score
  repeated Query required = 2;     // required clauses that do add to the score
  repeated Query optional = 3;     // optional clauses that add to the score
  repeated Query prohibited = 4;   // prohibited clauses that must not match
  int32 min_match = 5;             // minimum number of optional clauses that must match
}

message PhraseQuery {
  string field = 1;

  // Only set one of these.  A protobuf "oneof" was originally used, but it adds extra levels of indirection
  string text = 2;               // un-analyzed text that should yield multiple words when analyzed. ex: "Thomas Anderson"
  repeated string words = 3;     // un-analyzed list of words. ex: ["Yonik","Seeley"]
  repeated string terms = 4;     // analyzed list of terms as strings
  repeated bytes terms_bin = 5;  // analyzed list of binary (raw bytes) terms

  // TODO: add a parameter for slop?
  repeated int32 positions = 15; // optional positions of the terms
}


message FieldFacet {
  string field = 1;
  map<string, SearchOp> ops = 2;  // sub-facets or search operations performed per bucket
}

// A "domain" defines a set of documents to do computations over (like facets)
message Domain {
  string op_name = 1;                 // The name of a search operation that yields a set of documents. If missing
                                      // The first TopDocs operation in the request is assumed.
  Query root = 2;                     // Resets the domain to this root query.
  repeated string include_filter = 3; // Names of filters to apply (normally not needed unless a new root was selected)
                                      // A special name of "*" means all filters applied to the reference domain.
  repeated string exclude_filter = 4; // Names of filters to exclude (i.e. not apply) Used for multi-select faceting.
  repeated NamedQuery filter = 5;     // Additional named filters to apply
}

// Top-level response to a Search request
message SearchResponse {
  bytes request_id = 1;
  map<string, SearchResult> ops = 2;
  bool more = 15;  // if true, expect at least one more streaming response to the logical request.
}

message SearchResult {
  oneof kind {
    DocList docs = 1;
    FacetResult facet = 2;
  }
}

message DocList {
  sint64 matches = 1;
  float max_score = 2;
  map<string, Column> columns = 3;
  int64 offset = 4;
  bool more = 5; // expect more results to be streamed back?
}

// TODO: a column format for facets for better efficiency (so string names and protobuf tags aren't repeated for each bucket?)
// may be more efficient client language mapping as well?
// What about special buckets then?  Map to a column number?  See FacetResponse below for a prototype column response
message BucketList {
  repeated Bucket buckets = 1;
  sint64 total_buckets = 2;  // The total number of buckets *if* it was requested.  This can be expensive to calculate.
  int64 offset = 3;
  // TODO: a more flag if streaming for this bucket list?
}

message Bucket {
  Val val = 1;
  sint64 count = 2;
  map<string, SearchResult> ops = 3;
}

message FacetResult {
  sint64 total_buckets =  1; // The total number of buckets *if* it was requested.  This can be expensive to calculate.
  Column bucket_ids = 2;
  repeated int64 counts = 3;
  Columns columns = 4;  // other custom values requested for this facet, like min(price) for example
  int64 offset = 5;
}



//
//  Indexing
//

message UpdateRequest {
  // request_id is optional and opaque (server does not care what the value is).  If provided, the server will
  // use it in the UpdateResponse.  This is useful for the client to correlate requests and responses in
  // streaming RPCs.
  bytes request_id = 1;

  // stream_id is optional.  When in streaming mode,
  // Update messages in the same logical stream will be processed serially.  A stream_id of 0
  int64 stream_id = 2;

  Target collection = 3;

  // Documents represented as multiple rows... less efficient since field names are repeated for each document.
  // Using the same field order for each row will make things slightly more efficient.
  repeated Map docs = 4;

  // Column representation of a batch of documents.  All columns should have the same length.
  // For very sparse fields that you do not wish to represent as a column, use a special
  // field name of "_fields_" with a value of ColMap for per-document sparse values.  This will
  // effectively enable a mix of column oriented and row oriented.
  Columns columns = 5;

  enum CommitType {
    NO_COMMIT = 0;         // the default
    COMMIT = 1;            // ensure new data is searchable
    SILENT_COMMIT = 2;     // the commit will be "silent" (won't necessarily cause new searchers to be opened)
    // CONSISTENT_COMMIT = 3; // FUTURE - ensure distributed searchers will see new data
  }
  CommitType commit = 6;

  // Commit within this many microseconds.  Does not have an effect if commit is NO_COMMIT.
  // This parameter can be useful to ensure that too many commits aren't being done that can hurt
  // both indexing and search performance, but still places an upper bound on how stale the data can be.
  // If CommitType != NO_COMMIT, the default value of 0 causes an immediate commit before the response is sent,
  // while a positive value will not wait for the commit before the response is sent.
  uint64 commit_within_us = 7;
}

// The response to an update request, or one or more update requests in streaming mode.
message UpdateResponse {
  repeated SingleUpdateResponse responses = 1;
}

message SingleUpdateResponse {
  bytes request_id = 1;
  repeated UpdateError errors = 2;
}

message UpdateError {
  // docId... bytes? string?
  string error_message = 1;
  // for an invalid value for a field, we could actually give that field/value in a more structured way
}


// name : value
message NamedValue {
  string name = 1;
  Val val = 2;
}

message Map {
  // Unordered map of dynamically typed values.
  map<string, Val> fields = 1;
}

// like a Map, but the values are column types
message Columns {
  map<string, Column> columns = 1;
}

message Val {
  oneof kind {
    // Represents a null value.
    google.protobuf.NullValue null = 1;
    string s = 2;
    sint64 i = 3;  // since the encoding is the same, we don't bother distinguishing between 32 and 64 bit int
    double d = 4;
    float f = 5;
    bool b = 6;
    bytes bin = 7;
    Map map = 8;
    ArrVal arr = 9;
    ArrStr arr_s = 10;
    ArrInt arr_i = 11;
    ArrFloat arr_f = 12;
    ArrDouble arr_d = 13;
    ArrBin arr_bin = 14;
  }
}

message ArrVal {
  // Repeated field of dynamically typed values.
  repeated Val v = 1;
}

message ArrStr {
  repeated string v = 1;
}

message ArrInt {
  repeated sint64 v = 1;
}

message ArrFloat {
  repeated float v = 1;
}

message ArrDouble {
  repeated double v = 1;
}

message ArrBin {
  repeated bytes v = 1;
}

// Array of arrays, used in columns for multi-valued fields.  One could use
// ArrVal instead, but this has less indirection and stronger typing.
message ArrArrStr {
  repeated ArrStr v = 1;
}

message ArrArrInt {
  repeated ArrInt v = 1;
}

message ArrArrFloat {
  repeated ArrFloat v = 1;
}

message ArrArrDouble {
  repeated ArrDouble v = 1;
}

message ArrArrBin {
  repeated ArrBin v = 1;
}

// although the encoding is the same, the stub mapping is not and could blow up memory for large arrays
// if we always use 64 byte ints.
// TODO: if we can do custom decoding, an array that specifies a min/max would be even more efficient
message ArrInt32 {
  repeated sint32 v = 1;
}

message ColStr {
  // this will cause an additional tag (byte) per string value, but strings are normally somewhat larger anyway
  // repeated google.protobuf.StringValue v = 1;
  string missingVal = 1;
  repeated string v = 2;
}

// The distinction between a column and an array is that column values are somehow "nullable".
// This is a requirement to get different columns to "line up" if there mare missing values
// in some of them.
message Column {
  oneof kind {
    ColStr col_s = 1;
    ColInt col_i = 2;
    ColFloat col_f = 3;
    ColDouble col_d = 4;
    ArrArrStr multi_s = 5;  // name col_ss? (after dynamic field naming convention in solr)?
    ArrArrInt multi_i = 6;
    ArrArrFloat multi_f = 7;
    ArrArrDouble multi_d = 8;

    ColMap col_map = 14;
    ArrVal col_val = 15; // array-of-value is already nullable, so we don't have a separate column type for it
  }
}

message ColInt {
  sint64 missing_val = 1;
  // we could also use a bitset for missing values, but that might be slightly harder to use for some people?
  // bytes missing_bits = 3;
  repeated sint64 v = 2;
}

message ColFloat {
  float missing_val = 1;
  repeated float v = 2;
}

message ColDouble {
  double missing_val = 1;
  repeated double v = 2;
}

message ColMap {
  repeated Map v = 1;
}

