syntax = "proto3";

import "google/protobuf/struct.proto";
import "google/protobuf/wrappers.proto";

option java_multiple_files = true;
option java_package = "org.apache.solux.types";
option java_outer_classname = "SoluxTypes";
option objc_class_prefix = "Solux";

package solux.proto;


/*
 Using the well-known-type of google.protobuf.Struct doc = 1
 allows {"doc":{"myint":77, "mystr":"foo"}}
 Unfortunately, that's not enough types!
 Replicating Struct myself requires this really verbose JSON to send to evans:
{
  "doc": {
    "fields": {
      "myint": {
        "number_value": 77
      },
      "mystr": {
        "string_value": "foo"
      }
    }
  }
}
*/


// Proto notes:
// can't repeat oneof fields or map fields
// can't have map as value in map


message UpdateRequest {
  // TODO: need some sort of index identifier (tenant, collection, ???)

  // TODO:
  // possible parameters: commitWithin,
  // optional batchId - in streaming request/responses, used to tell what batch has been indexed
  // optional stream - what logical stream this batch is part of (don't reorder docs in the same stream)
  //   or should this just be a separate streaming request for a separate stream?  That might be more difficult for some clients.



  // TODO: should docs/columns be wrapped in "oneof" (if so, need wrapper for "repeated Map docs")

  // documents represented as multiple rows... less efficient since field names are repeated for each document
  repeated Map docs = 1;

  // Column representation of a batch of documents.  All columns should have the same length.
  // For very sparse columns that you do not wish to represent as columns, use a special
  // field name of "_fields_" with a value of ColMap for per-document sparse values.  This is
  // effectively a mix of column oriented and row oriented.
  Columns columns = 2;
}


// name : value
message NamedValue {
  string name = 1;
  Val val = 2;
}

message Map {
  // Unordered map of dynamically typed values.
  map<string, Val> fields = 1;
}

// like a Map, but the values are restricted to column types
message Columns {
  map<string, Column> columns = 1;
}

message Val {
  oneof kind {
    // Represents a null value.
    google.protobuf.NullValue null = 1;
    string s = 2;
    sint64 i = 3;  // since the encoding is the same, we don't bother distinguishing between 32 and 64 bit int
    double d = 4;
    float f = 5;
    bool b = 6;
    bytes bin = 7;
    Map map = 8;
    ArrVal arr = 9;
    ArrStr arr_s = 10;
    ArrInt arr_i = 11;
    ArrFloat arr_f = 12;
    ArrDouble arr_d = 13;
  }
}

message ArrVal {
  // Repeated field of dynamically typed values.
  repeated Val v = 1;
}

message ArrStr {
  repeated string v = 1;
}

message ArrInt {
  repeated sint64 v = 1;
}

message ArrFloat {
  repeated float v = 1;
}

message ArrDouble {
  repeated double v = 1;
}

// although the encoding is the same, the stub mapping is not and could blow up memory for large arrays
// if we always use 64 byte ints.
// TODO: if we can do custom decoding, an array that specifies a min/max would be even more efficient
message ArrInt32 {
  repeated sint32 v = 1;
}

message ColStr {
  // this will cause an additional tag (byte) per string value, but strings are normally somewhat larger anyway
  repeated google.protobuf.StringValue v = 1;
 /*
  optional string missingVal = 1;
  repeated string v = 2;
 */
}

// The distinction between a column and an array is that column values are somehow "nullable".
// This is a requirement to get different columns to "line up" if there mare missing values
// in some of them.
message Column {
  oneof kind {
    ColStr col_s = 1;
    ColInt col_i = 2;
    ColFloat col_f = 3;
    ColDouble col_d = 4;
    ColMap col_map = 14;
    ArrVal col_val = 15; // array-of-value is already nullable, so we don't have a separate column type for it
  }
}

message ColInt {
  optional sint64 missingVal = 1;
  repeated sint64 v = 2;
}

message ColFloat {
  optional float missingVal = 1;
  repeated float v = 2;
}

message ColDouble {
  optional double missingVal = 1;
  repeated double v = 2;
}

message ColMap {
  repeated Map v = 1;
}

