#pragma once
// Build-by-backing helpers for the NON-OWNING concrete response types (luxir::api).
//
// Response data is GENERATED by the engine, not decoded from the wire, so it must be
// allocated somewhere that outlives serialization: a caller-provided arena exposed as a
// std::pmr::memory_resource (the per-request arena; the engine adapts its allocator to
// one). Every luxir::api message type is trivially destructible, so nothing here
// registers a destructor - the arena is released wholesale and the views (span /
// map_view / indirect_view) just go away with it.
//
// The helpers return MUTABLE pointers/refs into arena storage for the engine to fill,
// and set the concrete view members to point at that storage. All build state lives in
// the message object itself (a map_view's data()+size() is its backing array + count),
// so a fresh response per streaming emit needs no external bookkeeping.
#include <cstring>
#include <memory>
#include <memory_resource>
#include <span>
#include <string_view>
#include <utility>
#include <vector>

#include <hpp_proto/indirect_view.hpp>

#include "luxir_types.hpp"

namespace luxir::api::build {

template<class T>
T* allocMessage(std::pmr::memory_resource& mr) {
  T* value = (T*)mr.allocate(sizeof(T), alignof(T));
  return new (value) T();
}

// Allocate n value-initialized T in the arena, point `target` at them, return the
// mutable array for index-fill. n is known up front (e.g. the batch doc count).
template <class T>
T* allocArray(std::span<const T>& target, std::size_t n, std::pmr::memory_resource& mr) {
  if (n == 0) { target = {}; return nullptr; }
  T* a = (T*)mr.allocate(sizeof(T) * n, alignof(T));
  std::uninitialized_value_construct_n(a, n);
  target = std::span<const T>(a, n);
  return a;
}

// Copy a transient string/bytes range into the arena and return a stable view.
inline std::string_view arenaStr(std::pmr::memory_resource& mr, std::string_view s) {
  if (s.empty()) return {};
  char* p = (char*)mr.allocate(s.size(), 1);
  std::memcpy(p, s.data(), s.size());
  return {p, s.size()};
}
inline ::hpp_proto::bytes_view arenaBytes(std::pmr::memory_resource& mr, std::span<const std::byte> s) {
  if (s.empty()) return {};
  std::byte* p = (std::byte*)mr.allocate(s.size(), 1);
  std::memcpy(p, s.data(), s.size());
  return ::hpp_proto::bytes_view(p, s.size());
}

// --- indirect_view<T> map: map_view<string_view, indirect_view<T>> ---
// Get-or-create a stable, mutable T* slot for `key`. `cap` is the maximum number of
// entries; the backing pair[] is allocated once at that capacity on first call and the
// span length tracks the count actually created. A repeated key returns the same T*.
// Each T is allocated separately, so its address is stable while siblings add other
// slots. Works for response ops (T=Val) and request ops (T=SearchOp). T's default ctor
// must not throw (it is placement-new'd into the arena) and T must be trivially
// destructible (the arena is released wholesale).
template <class T>
T* mapSlot(map_view<std::string_view, ::hpp_proto::indirect_view<T>>& m,
           std::size_t cap, std::string_view key, std::pmr::memory_resource& mr) {
  using IV = ::hpp_proto::indirect_view<T>;
  using Pair = std::pair<std::string_view, IV>;
  Pair* arr;
  std::size_t count = m.size();
  if (m.data() == nullptr) {
    arr = (Pair*)mr.allocate(sizeof(Pair) * cap, alignof(Pair));
    std::uninitialized_value_construct_n(arr, cap);
    count = 0;
  } else {
    arr = const_cast<Pair*>(m.data());
    for (std::size_t i = 0; i < count; i++) {
      if (arr[i].first == key) {
        return arr[i].second.pointer();
      }
    }
  }
  T* v = (T*)mr.allocate(sizeof(T), alignof(T));
  new (v) T();  // trivially destructible; variant arms default to monostate
  arr[count] = Pair{key, IV{v}};
  m = map_view<std::string_view, IV>(std::span<const Pair>(arr, count + 1));
  return v;
}

// Back-compat alias: the response-build call sites use opsSlot for the Val map.
inline Val* opsSlot(map_view<std::string_view, ::hpp_proto::indirect_view<Val>>& ops,
                    std::size_t cap, std::string_view key, std::pmr::memory_resource& mr) {
  return mapSlot<Val>(ops, cap, key, mr);
}

// --- columns map: map_view<string_view, Column> (Column by value) ---
// Get-or-create a mutable Column& slot for `field`. Same pre-sized backing-array scheme
// as opsSlot; `cap` is the number of fields that may be emitted. The caller fills the
// Column (e.g. col.kind.emplace<ColInt>()).
inline Column& columnSlot(map_view<std::string_view, Column>& cols, std::size_t cap,
                          std::string_view field, std::pmr::memory_resource& mr) {
  using Pair = std::pair<std::string_view, Column>;
  Pair* arr;
  std::size_t count = cols.size();
  if (cols.data() == nullptr) {
    arr = (Pair*)mr.allocate(sizeof(Pair) * cap, alignof(Pair));
    std::uninitialized_value_construct_n(arr, cap);
    count = 0;
  } else {
    arr = const_cast<Pair*>(cols.data());
    for (std::size_t i = 0; i < count; i++) {
      if (arr[i].first == field) {
        return arr[i].second;
      }
    }
  }
  arr[count].first = field;
  cols = map_view<std::string_view, Column>(std::span<const Pair>(arr, count + 1));
  return arr[count].second;
}

// Growable arena-backed builder for repeated fields whose final size is not known up
// front (multi-valued columns, fused doc lists). Backed by a std::pmr::vector over the
// arena; with a monotonic arena, deallocate is a no-op, so the buffer stays valid after
// the builder dies - finish()'s span remains usable until the arena is released. (Growth
// reallocations leak intermediate buffers into the monotonic arena, which is fine.)
template <class T>
class SpanBuilder {
  std::pmr::vector<T> buf;

public:
  explicit SpanBuilder(std::pmr::memory_resource& mr) : buf(&mr) {}
  void reserve(std::size_t n) { buf.reserve(n); }
  void push_back(const T& v) { buf.push_back(v); }
  template <class... A>
  T& emplace_back(A&&... a) { return buf.emplace_back(std::forward<A>(a)...); }
  void clear() { buf.clear(); }
  std::size_t size() const { return buf.size(); }
  std::span<const T> finish() const { return {buf.data(), buf.size()}; }
};

}  // namespace luxir::api::build
