#!/usr/bin/env python3
# Copyright 2020-2026 Yonik Seeley and Luxir contributors
# SPDX-License-Identifier: Apache-2.0

"""Generate KStemData.h from a Lucene checkout: generate_kstem_data.py /path/to/lucene."""

import argparse
from pathlib import Path
import re


def strings(source, name):
    # Strip comments first: countryNationality has a disabled Netherlands mapping.
    source = re.sub(r"/\*.*?\*/|//[^\n]*", "", source, flags=re.S)
    body = re.search(r"String\[\](?:\[\])? " + name + r" = \{(.*?)\n  \};", source, re.S)
    if body is None:
        raise ValueError(f"Missing Java array {name}")
    return re.findall(r'"([^"]*)"', body[1])


def generate(lucene):
    source_dir = lucene / "lucene/analysis/common/src/java/org/apache/lucene/analysis/en"
    source = (source_dir / "KStemmer.java").read_text()
    license_text = source[:source.index("package ")].replace("\u00a9", "(c)")
    groups = [("Exceptions", [(word, word, True) for word in strings(source, "exceptionWords")])]
    for name in ("directConflations", "countryNationality"):
        values = strings(source, name)
        if len(values) % 2:
            raise ValueError(f"Incomplete mapping in {name}")
        groups.append((name, [(values[i], values[i + 1], False) for i in range(0, len(values), 2)]))
    for i in range(1, 9):
        values = strings((source_dir / f"KStemData{i}.java").read_text(), "data")
        groups.append((f"KStemData{i}", [(word, "", False) for word in values]))
    for name in ("supplementDict", "properNouns"):
        groups.append((name, [(word, "", False) for word in strings(source, name)]))

    seen = set()
    mapped_endings = set()
    lines = []
    for name, entries in groups:
        lines.append(f"  // {name}")
        line = " "
        for key, root, exception in entries:
            if key in seen:
                raise ValueError(f"Duplicate key: {key}")
            seen.add(key)
            for word in (key, root):
                if not word.isascii() or (word and not re.fullmatch("[a-z]+", word)):
                    raise ValueError(f"Unexpected dictionary text: {word!r}")
            # Metadata terminates the key, so root lengths must stay below 'a'.
            if not 0 < len(key) < 64 or len(root) >= ord('a') or (exception and root != key):
                raise ValueError(f"Unrepresentable entry: {key!r}, {root!r}, {exception}")
            meta = 255 if exception else len(root)
            if root and not exception:
                if len(key) < 3:
                    raise ValueError(f"Mapping key too short for suffix screening: {key!r}")
                mapped_endings.add(key[-3:])
            record = f'"{key}\\{meta:03o}{"" if exception else root}"'
            if len(line) + 1 + len(record) > 100:
                lines.append(line)
                line = " "
            line += " " + record
        if line.strip():
            lines.append(line)

    return (license_text + "\n#pragma once\n\n"
            "// Generated by generate_kstem_data.py from Lucene KStemmer.java and KStemData1-8.java.\n"
            "// Records: <key><root length or 255><root>.\n"
            "// Root length 0 means no mapping; 255 means an exception with root equal to key.\n"
            "// Keys are lowercase ASCII; the metadata byte terminates each key.\n"
            "// Octal escapes are exactly three digits. Only the entire array has a trailing NUL.\n"
            "namespace luxir::kstem {\n\n"
            f"constexpr int entryCount = {len(seen)};\n"
            f"constexpr int shortEntryCount = {sum(len(key) <= 4 for key in seen)};\n"
            "// Three-letter endings of all direct-mapping keys, including nationalities.\n"
            f'constexpr char mappedEndings[] = "{"".join(sorted(mapped_endings))}";\n'
            "constexpr char data[] =\n" + "\n".join(lines) + ";\n\n"
            "} // namespace luxir::kstem\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("lucene", type=Path)
    args = parser.parse_args()
    Path(__file__).with_name("KStemData.h").write_text(generate(args.lucene))
