# Embed a binary file as a C++ byte array header.
# Usage: cmake -DFDS_IN=<bin> -DOUT_H=<header> -P cmake/embed_fds.cmake
file(READ "${FDS_IN}" _hex HEX)
string(LENGTH "${_hex}" _hexlen)
math(EXPR _nbytes "${_hexlen} / 2")
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _arr "${_hex}")
file(WRITE "${OUT_H}"
"// Generated by embed_fds.cmake - DO NOT EDIT. Embedded FileDescriptorSet.
#pragma once
namespace solux::detail {
inline constexpr unsigned char kSoluxFds[] = { ${_arr} };
inline constexpr unsigned kSoluxFdsLen = ${_nbytes}u;
} // namespace solux::detail
")
